# Generated by Django 5.1.5 on 2025-11-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_attachment_data_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
