# Generated by Django 5.1.5 on 2025-10-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_deal_category_deal_location_deal_max_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='deal',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
