# Generated by Django 5.1.5 on 2025-10-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_deal_is_verified_deal_rating_deal_verification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='seller_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
