# Generated by Django 5.1.5 on 2025-10-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_voucher_platform_commission_voucher_seller_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
        migrations.AlterField(
            model_name='deal',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
    ]
