# Generated by Django 5.1.5 on 2025-10-27 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('deals', '0004_voucher_platform_commission_voucher_seller_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
        migrations.AlterField(
            model_name='deal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
    ]
