# Generated by Django 5.1.5 on 2025-10-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_alter_deal_options_alter_deal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
    ]
