# Generated by Django 5.1.5 on 2025-11-01 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='main_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='deals.deal')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('deal', 'order')},
            },
        ),
    ]
