# Generated by Django 5.1.5 on 2025-11-04 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_deal_main_image_dealimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add new fields for affiliate platform
        migrations.AddField(
            model_name='deal',
            name='best_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        
        # Create StoreLink model
        migrations.CreateModel(
            name='StoreLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_url', models.URLField(max_length=500)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_links', to='deals.deal')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        
        # Create ClickTracking model
        migrations.CreateModel(
            name='ClickTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('store_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='deals.storelink')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        
        # Add unique constraint for store links
        migrations.AddConstraint(
            model_name='storelink',
            constraint=models.UniqueConstraint(fields=['deal', 'store_name'], name='unique_deal_store'),
        ),
        
        # Copy is_active to is_published
        migrations.RunSQL(
            "UPDATE deals_deal SET is_published = is_active;",
            reverse_sql="UPDATE deals_deal SET is_active = is_published;"
        ),
    ]
