# Generated by Django 5.1.5 on 2025-11-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_safe_model_cleanup'),
    ]

    operations = [
    ]
