# Generated by Django 5.1.5 on 2025-11-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0015_state_only_cleanup'),
    ]

    operations = [
        # Safe constraint removal
        migrations.RunSQL(
            """
            DO $$ 
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name='unique_deal_store') THEN
                    ALTER TABLE deals_storelink DROP CONSTRAINT unique_deal_store;
                END IF;
            END $$;
            """,
            reverse_sql="-- No reverse needed"
        ),
    ]
