# Generated by Django 5.1.5 on 2025-11-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0015_state_only_cleanup'),
    ]

    operations = [
        # Safe constraint removal
        migrations.RunSQL(
            """
            SELECT 1;
            """,
            reverse_sql="-- No reverse needed"
        ),
    ]
