# Generated by Django 5.1.5 on 2025-11-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0017_final_state_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='featured_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FeaturedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('deal', 'Deal'), ('seller', 'Seller')], max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('algorithm', models.CharField(choices=[('manual', 'Manual Selection'), ('likes', 'Most Liked'), ('views', 'Most Viewed'), ('clicks', 'Most Clicked'), ('subscription', 'Premium Subscription')], default='manual', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
