# Generated by Django 5.1.5 on 2025-11-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_google_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_conversation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('offer', 'New Offer'), ('favorite', 'Favorite Update'), ('system', 'System'), ('promotion', 'Promotion'), ('message', 'New Message')], default='system', max_length=20),
        ),
    ]
