# Generated by Django 5.1.5 on 2025-10-16 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_seller_business_license_seller_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='seller_logos/')),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='sellers.seller')),
            ],
            options={
                'db_table': 'seller_profiles',
            },
        ),
    ]
