# Generated by Django 5.1.5 on 2025-10-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto-Billing')], default='manual', max_length=10),
        ),
    ]
