# Generated by Django 5.1.5 on 2025-10-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_subscription_authorization_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paystack_plan_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paystack_subscription_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
