# Generated by Django 5.1.5 on 2025-10-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0008_subscription_paystack_plan_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='paystack_plan_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
