# Generated by Django 5.1.5 on 2025-10-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0009_subscriptionplan_paystack_plan_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
