# Generated by Django 5.1.5 on 2025-11-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0010_alter_sellerprofile_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='company_logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
