# Generated by Django 5.1.5 on 2025-11-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0011_seller_cover_image_sellerprofile_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='featured_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
